import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useContext } from 'react'
import TenantContext from '../../contexts/tenant'
import styles from '../../styles/Home.module.css'

const PostPage: NextPage = () => {
  const tenant = useContext(TenantContext);
  const router = useRouter();
  const { pid } = router.query

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Post: {pid}
        </h1>
        <p>tenant={tenant.name}</p>
        <ul>
          <li><Link href="/">Root</Link></li>
          <li><Link href="/posts/first">first</Link></li>
          <li><Link href="/posts/second">second</Link></li>
        </ul>
      </main>
    </div>
  )
}

export default PostPage
